services:
  - type: web
    name: whatsapp-bot
    env: python
    buildCommand: ""
    startCommand: gunicorn Twilio:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false